const plants = [
  { name: 'Trailing pothos', note: 'Low light friendly · 12cm pot', price: '£14', image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=900&q=85' },
  { name: 'Boston fern', note: 'For a cool, humid corner · 17cm pot', price: '£22', image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=85' },
  { name: 'Rubber plant', note: 'Deep green leaves · 21cm pot', price: '£36', image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=900&q=85' },
];
const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Home() {
  return <main>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="topbar"><a className="wordmark" href="#top" aria-label="Fern and Clay home"><i>F</i><span>Fern<br />&amp; Clay</span></a><nav aria-label="Main navigation"><a href="#plants">Plants</a><a href="#care">Plant care</a><a href="#workshops">Workshops</a><a href="#visit">Visit</a></nav><a className="nav-cta" href="#visit">Come by <Arrow /></a></header>
    <section className="hero" id="top" aria-label="Fern and Clay greenhouse"><div className="hero-copy"><p className="eyebrow">Stoke Newington · London</p><h1>Plants for<br /><em>slow living.</em></h1><p className="lede">A neighbourhood plant shop and working greenhouse. Grown with care, chosen for London homes.</p><a className="button button-light" href="#plants">See what&apos;s in <Arrow /></a></div><div className="hero-note"><span>01 — 06</span><p>Fogged glass. Warm earth. Something green to take home.</p></div></section>
    <section className="intro section" id="main"><p className="eyebrow">A small shop with room to breathe</p><div><h2>At the end of the garden path, beneath the old glass roof.</h2><p>Fern &amp; Clay is a place for good plants, proper pots and practical help. We keep the greenhouse warm, the kettle on, and the advice honest.</p><a className="text-link" href="#visit">Find us in N16 <Arrow /></a></div></section>
    <section className="plants section" id="plants"><div className="section-heading"><div><p className="eyebrow">This week in the greenhouse</p><h2>Ready to grow with you.</h2></div><a className="text-link" href="#visit">View all plants <Arrow /></a></div><div className="plant-grid">{plants.map((plant) => <article className="plant-card" key={plant.name}><div className="plant-image"><img src={plant.image} alt={plant.name} /><button aria-label={`Save ${plant.name}`} className="save">♡</button></div><div className="plant-meta"><div><h3>{plant.name}</h3><p>{plant.note}</p></div><strong>{plant.price}</strong></div></article>)}</div></section>
    <section className="care" id="care"><div className="care-image" role="img" aria-label="A hand tending leaves in a softly lit greenhouse" /><div className="care-copy"><p className="eyebrow">No nonsense plant care</p><h2>Not sure what&apos;s wrong with it?</h2><p>Bring in a photo, a leaf or the whole pot. We&apos;ll help you work out light, watering, pests and whether it&apos;s time for a repot—without making you feel silly.</p><ul><li><span>01</span> Ten-minute plant check-ins, free at the counter</li><li><span>02</span> Repotting service from £8 + compost</li><li><span>03</span> Care cards written for London flats</li></ul><a className="button button-dark" href="#visit">Ask us about your plant <Arrow /></a></div></section>
    <section className="workshops section" id="workshops"><div className="section-heading"><div><p className="eyebrow">At the potting bench</p><h2>Small workshops, good company.</h2></div><p className="heading-note">Upstairs, downstairs, or tucked around the old workbench: every class is small enough to ask questions.</p></div><div className="workshop-grid"><article className="workshop featured"><div><p className="eyebrow">Sat 12 October · 10am</p><h3>Make a winter window garden</h3><p>Build a low-light collection for a north-facing sill, including three plants, gravel and a terracotta pot.</p><a className="text-link" href="#visit">Reserve a place <Arrow /></a></div><span>£48<br /><small>8 places</small></span></article><article className="workshop"><p className="eyebrow">Thu 17 October · 6.30pm</p><h3>Houseplant troubleshooting</h3><p>Bring photographs and questions. Tea, notes and a gentle rescue plan included.</p><a className="text-link" href="#visit">£18 · Book <Arrow /></a></article><article className="workshop"><p className="eyebrow">Sun 27 October · 11am</p><h3>Terracotta &amp; trailing things</h3><p>Pot up a vine or fern, learn the basics, and leave with a very good windowsill.</p><a className="text-link" href="#visit">£35 · Book <Arrow /></a></article></div></section>
    <section className="delivery"><div><p className="eyebrow">From our greenhouse to your door</p><h2>Local delivery, done gently.</h2><p>We deliver plants, pots and soil within N16, N4, N5 and N8 every Thursday and Saturday. Orders placed by 2pm usually make the next run.</p><a className="button button-light" href="#visit">Delivery details <Arrow /></a></div><div className="delivery-stamp"><span>Fern &amp; Clay</span><b>Locally<br />grown</b><span>Stoke Newington</span></div></section>
    <section className="visit section" id="visit"><div className="visit-image" role="img" aria-label="A brick-fronted independent plant shop in Stoke Newington" /><div className="visit-copy"><p className="eyebrow">Come in from the cold</p><h2>Visit the greenhouse.</h2><address>48 Albion Road<br />Stoke Newington<br />London N16 9JU</address><a className="text-link" href="https://maps.google.com/?q=48+Albion+Road+Stoke+Newington+London+N16+9JU">Open in maps <Arrow /></a><div className="hours"><p><b>Shop &amp; greenhouse</b><br />Tuesday–Friday 10–6<br />Saturday 9–6<br />Sunday 10–4<br /><em>Closed Mondays</em></p><p><b>Getting here</b><br />8 min walk from<br />Stoke Newington Church St.<br /><em>Step-free via side gate</em></p></div></div></section>
    <footer><div className="footer-mark"><i>F</i><span>Fern &amp; Clay<br /><small>Plant shop &amp; greenhouse</small></span></div><p>Good things grow slowly.</p><div><a href="#visit">Instagram</a><a href="#visit">hello@fernandclay.co.uk</a></div></footer>
  </main>;
}
