import Link from "next/link";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const team = [["chef-one", "Executive chef", "Matteo Ricci", "Matteo brings the sunshine of his native Puglia to every plate, with an eye for restraint and a deep respect for tradition."], ["chef-two", "Head sommelier", "Elena Bianchi", "Elena's cellar is a love story written in Italian wine — unexpected, expressive, and always ready to be shared."], ["chef-three", "General manager", "Sofia Romano", "Sofia makes every table feel like the best one in the house. Her hospitality is our secret ingredient."]];

export default function AboutPage() {
  return <div className="inner-page"><Navbar active="about" /><main><section className="page-hero about-hero"><p className="eyebrow gold">Since 1994</p><h1>Made with heart.<br /><em>Served with soul.</em></h1></section><section className="history section-pad"><div className="history-image" role="img" aria-label="Italian restaurant interior" /><div><p className="eyebrow gold">Our history</p><h2>Born from a long table in <em>Napoli.</em></h2><p>Italiano began with a battered notebook of recipes, a wooden pasta board, and the belief that a restaurant should feel like an invitation. In 1994, founders Lucia and Marco Bellini opened our doors with just twelve tables and an ambitious little kitchen.</p><p>Three decades on, the room is a little larger, but the idea is unchanged: honest food, generous hospitality, and a reason to stay for one more glass of wine.</p></div></section><section className="team section-pad"><div className="team-intro"><p className="eyebrow gold">The people behind the plates</p><h2>Meet the <em>famiglia.</em></h2></div><div className="team-grid">{team.map(([photo, role, name, bio]) => <article key={name}><div className={`team-photo ${photo}`} role="img" aria-label={`${role} portrait`} /><p className="eyebrow gold">{role}</p><h3>{name}</h3><p>{bio}</p></article>)}</div></section><section className="reserve-panel"><div><p className="eyebrow gold">The table is set</p><h2>Join our story.</h2></div><Link className="button button-light" href="/#reserve">Reserve a table <span>→</span></Link></section></main><Footer /></div>;
}
